Repository yogevbd/enforce-label-action, pull requests merged in 2020-04, with the labels that each got.

#4 Add yml file
  .github/main.workflow
  .github/workflows/enforce-labels.yml
  README.md
Labels: enhancement

#5 Fix imports
  .github/workflows/enforce-labels.yml
  README.md
Labels: bug

#7 Use github/core package
  .github/workflows/enforce-labels.yml
  .gitignore
  Dockerfile
  action.yml
  lib/entrypoint.sh
  lib/request.js
  lib/run.js
  package-lock.json
  package.json
  src/main.ts
  tsconfig.json
Labels: bug, wontfix

#13 Fix main.ts
  action.yml
  src/main.ts
Labels: bug

#15 fix: `with` instead of `env`
  README.md
Labels: bug

#16 Add description text support
  .github/workflows/enforce-labels.yml
  README.md
  action.yml
  src/main.ts
Labels: enhancement
